// Code generated by cmd/coveragegen; DO NOT EDIT.

package forward

var sdkCoverageCatalog = map[string][]CoverageOperation{
	"AI.AddMessage": {
		{Method: "POST", Route: "/api/ai-chats/{chatId}/messages"},
	},
	"AI.DeleteChat": {
		{Method: "DELETE", Route: "/api/ai-chats/{chatId}"},
	},
	"AI.GetChat": {
		{Method: "GET", Route: "/api/ai-chats/{chatId}"},
	},
	"AI.ListChats": {
		{Method: "GET", Route: "/api/ai-chats"},
	},
	"AI.ListMessages": {
		{Method: "GET", Route: "/api/ai-chats/{chatId}/messages"},
	},
	"AI.RenameChat": {
		{Method: "PATCH", Route: "/api/ai-chats/{chatId}"},
	},
	"AI.StartChat": {
		{Method: "POST", Route: "/api/ai-chats"},
	},
	"AI.StartChatOperation": {
		{Method: "GET", Route: "/api/ai-chats/{chatId}"},
		{Method: "POST", Route: "/api/ai-chats"},
	},
	"AIAssist.AskNQEDocs": {
		{Method: "POST", Route: "/api/nqe/doc-assists"},
	},
	"AIAssist.GenerateNQEQuery": {
		{Method: "POST", Route: "/api/nqe/query-assists"},
	},
	"AIAssist.GeneratePredictCLI": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/devices/{device}/cli-assists"},
	},
	"AIAssist.GeneratePredictOverview": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/overview-assists"},
	},
	"AIAssist.SuggestNQEDocFollowups": {
		{Method: "POST", Route: "/api/nqe/doc-assists/{docAssistId}/followup"},
	},
	"AIAssist.SummarizeChangeImpact": {
		{Method: "POST", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/impact-summary-assists"},
	},
	"AIAssist.SummarizeConfigDiff": {
		{Method: "POST", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/config-summary-assists"},
	},
	"AIAssist.SummarizeNQEQuery": {
		{Method: "POST", Route: "/api/nqe/summary-assists"},
	},
	"AccessControl.AddLabels": {
		{Method: "PATCH", Route: "/api/access-control-groups"},
	},
	"AccessControl.CreateDeviceAccessLabel": {
		{Method: "POST", Route: "/api/device-access-labels"},
	},
	"AccessControl.CreateGroup": {
		{Method: "POST", Route: "/api/access-control-groups"},
	},
	"AccessControl.DeleteDeviceAccessLabel": {
		{Method: "DELETE", Route: "/api/device-access-labels/{labelId}"},
	},
	"AccessControl.DeleteGroup": {
		{Method: "DELETE", Route: "/api/access-control-groups/{groupId}"},
	},
	"AccessControl.DeviceAccessLabelNames": {
		{Method: "GET", Route: "/api/device-access-labels"},
	},
	"AccessControl.GroupNames": {
		{Method: "GET", Route: "/api/access-control-groups"},
	},
	"AccessControl.ListDeviceAccessLabels": {
		{Method: "GET", Route: "/api/device-access-labels"},
	},
	"AccessControl.ListGroups": {
		{Method: "GET", Route: "/api/access-control-groups"},
	},
	"AccessControl.RemoveLabels": {
		{Method: "PATCH", Route: "/api/access-control-groups"},
	},
	"AccessControl.SetGroupNetworkRole": {
		{Method: "POST", Route: "/api/access-control-groups/{groupId}/network-roles/{networkId}"},
	},
	"AccessControl.UpdateDeviceAccessLabel": {
		{Method: "PATCH", Route: "/api/device-access-labels/{labelId}"},
	},
	"AccessControl.UpdateGroup": {
		{Method: "POST", Route: "/api/access-control-groups/{groupId}"},
	},
	"Admin.AddSupportedOrganization": {
		{Method: "POST", Route: "/api/users/{userId}/supported-orgs"},
	},
	"Admin.CreateOrganizationUser": {
		{Method: "POST", Route: "/api/orgs/{orgId}/users"},
	},
	"Admin.DeleteUser": {
		{Method: "DELETE", Route: "/api/users/{userId}"},
	},
	"Admin.GrantOrganizationAdmin": {
		{Method: "POST", Route: "/api/users/{userId}/roles/org/ADMIN"},
	},
	"Admin.ListNetworks": {
		{Method: "GET", Route: "/api/admin/networks"},
	},
	"Admin.ListUsers": {
		{Method: "GET", Route: "/api/admin/users"},
	},
	"Admin.LookupUser": {
		{Method: "GET", Route: "/api/admin/users/{idOrUsername}"},
	},
	"Admin.PatchUser": {
		{Method: "PATCH", Route: "/api/users/{userId}"},
	},
	"Admin.SetSupportedOrganizations": {
		{Method: "PUT", Route: "/api/users/{userId}/supported-orgs"},
	},
	"Aliases.Deactivate": {
		{Method: "DELETE", Route: "/api/snapshots/{snapshotId}/aliases/{name}"},
	},
	"Aliases.Get": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/aliases/{name}"},
	},
	"Aliases.List": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/aliases"},
	},
	"Aliases.Put": {
		{Method: "PUT", Route: "/api/snapshots/{snapshotId}/aliases/{name}"},
	},
	"AuditLogs.List": {
		{Method: "GET", Route: "/api/audit-logs"},
	},
	"Backups.GetS3Storage": {
		{Method: "GET", Route: "/api/backup-settings/storage"},
	},
	"Backups.GetSettings": {
		{Method: "GET", Route: "/api/backup-settings"},
	},
	"Backups.Last": {
		{Method: "GET", Route: "/api/backups"},
	},
	"Backups.SetS3BucketOwnership": {
		{Method: "POST", Route: "/api/backup-settings"},
	},
	"Backups.Trigger": {
		{Method: "POST", Route: "/api/backups"},
	},
	"Backups.UpdateS3Storage": {
		{Method: "PATCH", Route: "/api/backup-settings/storage"},
	},
	"Backups.UpdateSettings": {
		{Method: "PATCH", Route: "/api/backup-settings"},
	},
	"Banners.Create": {
		{Method: "POST", Route: "/api/custom-banners"},
	},
	"Banners.List": {
		{Method: "GET", Route: "/api/custom-banners"},
	},
	"Banners.Replace": {
		{Method: "PUT", Route: "/api/custom-banners/{bannerId}"},
	},
	"Browser.CurrentSession": {
		{Method: "GET", Route: "/api/users/current"},
	},
	"Browser.CurrentUser": {
		{Method: "GET", Route: "/api/users/current"},
	},
	"Browser.Impersonate": {
		{Method: "GET", Route: "/api/admin/impersonate"},
	},
	"Browser.ImpersonateWithServiceCredential": {
		{Method: "GET", Route: "/api/admin/impersonate"},
	},
	"Browser.Login": {
		{Method: "GET", Route: "/api/public/csrf"},
		{Method: "GET", Route: "/login"},
		{Method: "POST", Route: "/login"},
	},
	"Browser.LoginLegacy": {
		{Method: "POST", Route: "/login"},
	},
	"Browser.LoginPageCSRF": {
		{Method: "GET", Route: "/login"},
	},
	"Browser.PublicCSRFAPI": {
		{Method: "GET", Route: "/api/public/csrf"},
	},
	"Browser.SAMLAssertionConsumer": {
		{Method: "POST", Route: "/login/saml2/sso/{registrationId}"},
	},
	"Browser.SAMLAuthenticationRequest": {
		{Method: "GET", Route: "/saml2/authenticate/{registrationId}"},
	},
	"CVEIndex.Delete": {
		{Method: "DELETE", Route: "/api/cve-index"},
	},
	"CVEIndex.Download": {
		{Method: "GET", Route: "/api/cve-index"},
	},
	"CVEIndex.Metadata": {
		{Method: "GET", Route: "/api/cve-index"},
	},
	"CVEIndex.Put": {
		{Method: "PUT", Route: "/api/cve-index"},
	},
	"Checks.Create": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}/checks"},
	},
	"Checks.CreatePersistent": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}/checks"},
	},
	"Checks.Deactivate": {
		{Method: "DELETE", Route: "/api/snapshots/{snapshotId}/checks/{checkId}"},
	},
	"Checks.DeactivateAll": {
		{Method: "DELETE", Route: "/api/snapshots/{snapshotId}/checks"},
	},
	"Checks.ExistingNames": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/checks"},
	},
	"Checks.ForScoring": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/checks"},
	},
	"Checks.Get": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/checks/{checkId}"},
	},
	"Checks.List": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/checks"},
	},
	"Checks.ListPredefined": {
		{Method: "GET", Route: "/api/predefinedChecks"},
	},
	"ClassicDevices.Create": {
		{Method: "POST", Route: "/api/networks/{networkId}/classic-devices"},
	},
	"ClassicDevices.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/classic-devices/{deviceName}"},
	},
	"ClassicDevices.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/classic-devices/{deviceName}"},
	},
	"ClassicDevices.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/classic-devices"},
	},
	"ClassicDevices.ListTestStatuses": {
		{Method: "GET", Route: "/api/networks/{networkId}/classic-devices"},
	},
	"ClassicDevices.Patch": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/classic-devices/{deviceName}"},
	},
	"ClassicDevices.Put": {
		{Method: "PUT", Route: "/api/networks/{networkId}/classic-devices/{deviceName}"},
	},
	"ClassicDevices.PutBatch": {
		{Method: "POST", Route: "/api/networks/{networkId}/classic-devices"},
	},
	"CloudAccounts.AWSAssumeRoleExternalID": {
		{Method: "GET", Route: "/api/networks/{networkId}/cloudAccounts/aws/assumeRole/externalId"},
	},
	"CloudAccounts.Create": {
		{Method: "POST", Route: "/api/networks/{networkId}/cloudAccounts"},
	},
	"CloudAccounts.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/cloudAccounts/{accountName}"},
	},
	"CloudAccounts.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/cloudAccounts"},
	},
	"CloudAccounts.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/cloudAccounts"},
	},
	"CloudAccounts.Test": {
		{Method: "POST", Route: "/api/networks/{networkId}/cloudAccounts/{accountName}/test"},
	},
	"CloudAccounts.Update": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/cloudAccounts/{accountName}"},
	},
	"CloudAccounts.UpdateCredential": {
		{Method: "POST", Route: "/api/networks/{networkId}/cloudAccounts/{accountName}/credential"},
	},
	"CloudManagedSetups.CreateMist": {
		{Method: "POST", Route: "/api/networks/{networkId}/cloud-managed-setups"},
	},
	"CloudManagedSetups.DeleteMist": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/cloud-managed-setups/{setupName}"},
	},
	"CloudManagedSetups.DiscoverMist": {
		{Method: "POST", Route: "/api/networks/{networkId}/cloud-managed-setups/{setupName}"},
	},
	"CloudManagedSetups.ListMist": {
		{Method: "GET", Route: "/api/networks/{networkId}/cloud-managed-setups"},
	},
	"CollectionSchedules.Create": {
		{Method: "POST", Route: "/api/networks/{networkId}/collection-schedules"},
	},
	"CollectionSchedules.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/collection-schedules/{scheduleId}"},
	},
	"CollectionSchedules.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/collection-schedules/{scheduleId}"},
	},
	"CollectionSchedules.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/collection-schedules"},
	},
	"CollectionSchedules.Replace": {
		{Method: "PUT", Route: "/api/networks/{networkId}/collection-schedules/{scheduleId}"},
	},
	"Collections.DeviceStatuses": {
		{Method: "GET", Route: "/api/networks/{networkId}/device-statuses"},
	},
	"CollectorTasks.Get": {
		{Method: "GET", Route: "/api/collector-tasks/{taskId}"},
	},
	"CollectorTasks.GetWithSubTasks": {
		{Method: "GET", Route: "/api/collector-tasks/{taskId}"},
	},
	"CollectorTasks.List": {
		{Method: "GET", Route: "/api/collector-tasks"},
	},
	"CollectorTasks.Progress": {
		{Method: "GET", Route: "/api/collector-tasks"},
	},
	"CollectorTasks.SnapshotProgress": {
		{Method: "GET", Route: "/api/collector-tasks"},
	},
	"CollectorTasks.Start": {
		{Method: "POST", Route: "/api/collector-tasks"},
	},
	"CollectorTasks.StartCollectionOperation": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
		{Method: "POST", Route: "/api/collector-tasks"},
	},
	"CollectorTasks.StartOperation": {
		{Method: "GET", Route: "/api/collector-tasks/{taskId}"},
		{Method: "POST", Route: "/api/collector-tasks"},
	},
	"CollectorTasks.Stop": {
		{Method: "POST", Route: "/api/collector-tasks/{taskId}"},
	},
	"CollectorTasks.SubTasksAt": {
		{Method: "GET", Route: "/api/collector-tasks/{taskId}"},
	},
	"Collectors.Attach": {
		{Method: "PUT", Route: "/api/networks/{networkId}/collector"},
	},
	"Collectors.Attachment": {
		{Method: "GET", Route: "/api/networks/{networkId}/collector"},
	},
	"Collectors.Delete": {
		{Method: "DELETE", Route: "/api/collectors/{collectorIdOrName}"},
	},
	"Collectors.GetOrganizationSettings": {
		{Method: "GET", Route: "/api/collection-settings"},
	},
	"Collectors.GetSettings": {
		{Method: "GET", Route: "/api/collectors/{collectorId}/collection-settings"},
	},
	"Collectors.List": {
		{Method: "GET", Route: "/api/collectors"},
	},
	"Collectors.PatchOrganizationSettings": {
		{Method: "PATCH", Route: "/api/collection-settings"},
	},
	"Collectors.PatchSettings": {
		{Method: "PATCH", Route: "/api/collectors/{collectorId}/collection-settings"},
	},
	"Collectors.Register": {
		{Method: "POST", Route: "/api/collectors"},
	},
	"Collectors.SetPerformanceCollection": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/performance/settings"},
	},
	"Compatibility.Checks": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/checks"},
	},
	"Compatibility.ListSnapshots": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Compatibility.StartCollectorTask": {
		{Method: "POST", Route: "/api/collector-tasks"},
	},
	"Configuration.GetDeployment": {
		{Method: "GET", Route: "/api/deployment-config/{property}"},
	},
	"Configuration.SetDeployment": {
		{Method: "PUT", Route: "/api/deployment-config/{property}"},
	},
	"ControllerManagedSetups.Create": {
		{Method: "POST", Route: "/api/networks/{networkId}/controller-managed-setups"},
	},
	"ControllerManagedSetups.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/controller-managed-setups/{setupName}"},
	},
	"ControllerManagedSetups.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/controller-managed-setups"},
	},
	"ControllerManagedSetups.Patch": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/controller-managed-setups/{setupName}"},
	},
	"Credentials.CreateCLI": {
		{Method: "POST", Route: "/api/networks/{networkId}/cli-credentials"},
	},
	"Credentials.CreateHTTP": {
		{Method: "POST", Route: "/api/networks/{networkId}/http-credentials"},
	},
	"Credentials.CreateSNMP": {
		{Method: "POST", Route: "/api/networks/{networkId}/snmpCredentials"},
	},
	"Credentials.CreateSNMPCredential": {
		{Method: "POST", Route: "/api/networks/{networkId}/snmpCredentials"},
	},
	"Credentials.DeleteCLI": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/cli-credentials/{credentialId}"},
	},
	"Credentials.DeleteHTTP": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/http-credentials/{credentialId}"},
	},
	"Credentials.DeleteSNMP": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/snmpCredentials/{credentialId}"},
	},
	"Credentials.GetCLI": {
		{Method: "GET", Route: "/api/networks/{networkId}/cli-credentials/{credentialId}"},
	},
	"Credentials.GetHTTP": {
		{Method: "GET", Route: "/api/networks/{networkId}/http-credentials/{credentialId}"},
	},
	"Credentials.ListCLI": {
		{Method: "GET", Route: "/api/networks/{networkId}/cli-credentials"},
	},
	"Credentials.ListHTTP": {
		{Method: "GET", Route: "/api/networks/{networkId}/http-credentials"},
	},
	"Credentials.ListSNMP": {
		{Method: "GET", Route: "/api/networks/{networkId}/snmpCredentials"},
	},
	"Credentials.ListSNMPCredentials": {
		{Method: "GET", Route: "/api/networks/{networkId}/snmpCredentials"},
	},
	"Credentials.UpdateCLI": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/cli-credentials/{credentialId}"},
	},
	"Credentials.UpdateHTTP": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/http-credentials/{credentialId}"},
	},
	"Credentials.UpdateHTTPWithResult": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/http-credentials/{credentialId}"},
	},
	"Credentials.UpdateSNMP": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/snmpCredentials/{credentialId}"},
	},
	"DataConnectors.Add": {
		{Method: "POST", Route: "/api/networks/{networkId}/data-connectors"},
	},
	"DataConnectors.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/data-connectors/{name}"},
	},
	"DataConnectors.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/data-connectors/{name}"},
	},
	"DataConnectors.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/data-connectors"},
	},
	"DataConnectors.Test": {
		{Method: "POST", Route: "/api/networks/{networkId}/data-connectors/{name}"},
	},
	"DataConnectors.Update": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/data-connectors/{name}"},
	},
	"DataFiles.Add": {
		{Method: "POST", Route: "/api/data-files"},
	},
	"DataFiles.AddToNetwork": {
		{Method: "POST", Route: "/api/networks/{networkId}/data-files/{dataFileName}"},
	},
	"DataFiles.AssessReplacement": {
		{Method: "POST", Route: "/api/data-files/{dataFileName}"},
	},
	"DataFiles.Content": {
		{Method: "GET", Route: "/api/data-files/{dataFileName}"},
	},
	"DataFiles.Delete": {
		{Method: "DELETE", Route: "/api/data-files/{dataFileName}"},
	},
	"DataFiles.InferSchema": {
		{Method: "POST", Route: "/api/data-files"},
	},
	"DataFiles.List": {
		{Method: "GET", Route: "/api/data-files"},
	},
	"DataFiles.ListForNetwork": {
		{Method: "GET", Route: "/api/networks/{networkId}/data-files"},
	},
	"DataFiles.Patch": {
		{Method: "PATCH", Route: "/api/data-files/{dataFileName}"},
	},
	"DataFiles.RemoveFromNetwork": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/data-files/{dataFileName}"},
	},
	"DataFiles.ReplaceContent": {
		{Method: "POST", Route: "/api/data-files/{dataFileName}"},
	},
	"DataFiles.Schema": {
		{Method: "GET", Route: "/api/data-files/{dataFileName}/schema"},
	},
	"DeviceTags.AddBatch": {
		{Method: "POST", Route: "/api/networks/{networkId}/device-tags"},
	},
	"DeviceTags.AddBatchTo": {
		{Method: "POST", Route: "/api/networks/{networkId}/device-tags"},
	},
	"DeviceTags.DeleteTag": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/device-tags/{tagName}"},
	},
	"DeviceTags.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/device-tags"},
	},
	"DeviceTags.RemoveBatchFrom": {
		{Method: "POST", Route: "/api/networks/{networkId}/device-tags"},
	},
	"DeviceTags.UpdateTag": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/device-tags/{tagName}"},
	},
	"Devices.DownloadFile": {
		{Method: "GET", Route: "/api/networks/{networkId}/devices/{deviceName}/files/{fileName}"},
	},
	"Devices.DownloadFileHead": {
		{Method: "GET", Route: "/api/networks/{networkId}/devices/{deviceName}/files/{fileName}"},
	},
	"Devices.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/devices/{deviceIdOrName}"},
	},
	"Devices.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/devices"},
	},
	"Devices.ListFiles": {
		{Method: "GET", Route: "/api/networks/{networkId}/devices/{deviceIdOrName}/files"},
	},
	"Devices.Missing": {
		{Method: "GET", Route: "/api/networks/{networkId}/missing-devices"},
	},
	"Diffs.Checks": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/checks"},
	},
	"Diffs.ChecksCount": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/checks"},
	},
	"Diffs.ConnectivityDiffLocationPair": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/subnet-connectivity"},
	},
	"Diffs.ConnectivityDiffLocations": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/subnet-connectivity"},
	},
	"Diffs.Count": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/acl"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/cloud-acl"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/cloud-objects"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/devices"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/interfaces"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/l2"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/routing-loop/count"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/topology"},
	},
	"Diffs.Devices": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/devices"},
	},
	"Diffs.Files": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/files"},
	},
	"Diffs.FilesCount": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/files"},
	},
	"Diffs.MaterialSummary": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/acl"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/checks"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/cloud-acl"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/cloud-objects"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/devices"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/files"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/interfaces"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/l2"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/routing-loop/count"},
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/topology"},
	},
	"Diffs.SubnetConnectivity": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/subnet-connectivity"},
	},
	"Diffs.WaitForSubnetConnectivity": {
		{Method: "GET", Route: "/api/diffs/{snapshotAId}/{snapshotBId}/subnet-connectivity"},
	},
	"Endpoints.AddBatch": {
		{Method: "POST", Route: "/api/networks/{networkId}/endpoints"},
	},
	"Endpoints.ApprovedCLICommands": {
		{Method: "GET", Route: "/api/approved-cli-commands"},
	},
	"Endpoints.CreateProfile": {
		{Method: "POST", Route: "/api/endpoint-profiles"},
	},
	"Endpoints.CreateProfileDefinition": {
		{Method: "POST", Route: "/api/endpoint-profiles"},
	},
	"Endpoints.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/endpoints/{name}"},
	},
	"Endpoints.DeleteProfile": {
		{Method: "DELETE", Route: "/api/endpoint-profiles/{profileId}"},
	},
	"Endpoints.GetProfile": {
		{Method: "GET", Route: "/api/endpoint-profiles/{profileId}"},
	},
	"Endpoints.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/endpoints"},
	},
	"Endpoints.ListProfiles": {
		{Method: "GET", Route: "/api/endpoint-profiles"},
	},
	"Endpoints.ListTestStatuses": {
		{Method: "GET", Route: "/api/networks/{networkId}/endpoints"},
	},
	"Endpoints.Patch": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/endpoints/{name}"},
	},
	"Endpoints.UpdateProfile": {
		{Method: "PATCH", Route: "/api/endpoint-profiles/{profileId}"},
	},
	"Integrations.CreateInfoblox": {
		{Method: "POST", Route: "/api/integrations/infoblox/instances"},
	},
	"Integrations.CreateRapid7": {
		{Method: "POST", Route: "/api/networks/{networkId}/rapid7-sources"},
	},
	"Integrations.DeleteServiceNow": {
		{Method: "DELETE", Route: "/api/integrations/servicenow"},
	},
	"Integrations.EnableServiceNowCMDB": {
		{Method: "POST", Route: "/api/integrations/servicenow-cmdb"},
	},
	"Integrations.GetServiceNow": {
		{Method: "GET", Route: "/api/integrations/servicenow"},
	},
	"Integrations.ListInfoblox": {
		{Method: "GET", Route: "/api/integrations/infoblox/instances"},
	},
	"Integrations.ListInfobloxLegacy": {
		{Method: "GET", Route: "/api/integrations/infoblox"},
	},
	"Integrations.ListRapid7": {
		{Method: "GET", Route: "/api/networks/{networkId}/end-host-scanners"},
	},
	"Integrations.PatchServiceNow": {
		{Method: "PATCH", Route: "/api/integrations/servicenow"},
	},
	"Integrations.SaveServiceNowCMDB": {
		{Method: "POST", Route: "/api/integrations/servicenow-cmdb/configuration"},
	},
	"Integrations.ServiceNowCMDBSchema": {
		{Method: "POST", Route: "/api/integrations/servicenow-cmdb"},
	},
	"Integrations.UpdateRapid7": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/rapid7-sources/{sourceName}"},
	},
	"JumpServers.Create": {
		{Method: "POST", Route: "/api/networks/{networkId}/jumpServers"},
	},
	"JumpServers.CreateLegacy": {
		{Method: "POST", Route: "/api/networks/{networkId}/jumpServers"},
	},
	"JumpServers.CreateWithPassword": {
		{Method: "POST", Route: "/api/networks/{networkId}/jumpServers"},
	},
	"JumpServers.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/jumpServers"},
	},
	"Licensing.Apply": {
		{Method: "POST", Route: "/api/licenses"},
	},
	"Licensing.Decode": {
		{Method: "POST", Route: "/api/licenses"},
	},
	"Licensing.Fingerprint": {
		{Method: "GET", Route: "/api/vm/instanceId"},
	},
	"Licensing.InvalidateForOrg": {
		{Method: "POST", Route: "/api/orgs/{orgId}/licenses/{licenseId}"},
	},
	"Licensing.ListForOrg": {
		{Method: "GET", Route: "/api/orgs/{orgId}/licenses"},
	},
	"Licensing.RemoveAllForOrg": {
		{Method: "DELETE", Route: "/api/orgs/{orgId}/licenses"},
	},
	"Locations.Assign": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/atlas"},
	},
	"Locations.Create": {
		{Method: "POST", Route: "/api/networks/{networkId}/locations"},
	},
	"Locations.CreateCluster": {
		{Method: "POST", Route: "/api/networks/{networkId}/locations/{locationId}/clusters"},
	},
	"Locations.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/locations"},
	},
	"Locations.ListClusters": {
		{Method: "GET", Route: "/api/networks/{networkId}/locations/{locationId}/clusters"},
	},
	"Locations.PatchCluster": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/locations/{locationId}/clusters/{clusterName}"},
	},
	"NQE.Diff": {
		{Method: "POST", Route: "/api/nqe-diffs/{before}/{after}"},
	},
	"NQE.ListQueries": {
		{Method: "GET", Route: "/api/nqe/queries"},
	},
	"NQE.Result": {
		{Method: "GET", Route: "/api/networks/{networkId}/nqe-executions/{executionKey}/result"},
	},
	"NQE.ResultJSONLines": {
		{Method: "GET", Route: "/api/networks/{networkId}/nqe-executions/{executionKey}/result"},
	},
	"NQE.Run": {
		{Method: "POST", Route: "/api/nqe"},
	},
	"NQE.Schema": {
		{Method: "GET", Route: "/api/nqe/schema"},
	},
	"NQE.SchemaAt": {
		{Method: "GET", Route: "/api/nqe/schema"},
	},
	"NQE.Start": {
		{Method: "POST", Route: "/api/networks/{networkId}/nqe-executions"},
	},
	"NQE.StartOperation": {
		{Method: "GET", Route: "/api/networks/{networkId}/nqe-executions/{executionKey}"},
		{Method: "POST", Route: "/api/networks/{networkId}/nqe-executions"},
	},
	"NQE.Status": {
		{Method: "GET", Route: "/api/networks/{networkId}/nqe-executions/{executionKey}"},
	},
	"NQERepository.AddDirectory": {
		{Method: "POST", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.AddQuery": {
		{Method: "POST", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.Commit": {
		{Method: "POST", Route: "/api/nqe/repos/org/commits"},
	},
	"NQERepository.CommitDryRun": {
		{Method: "POST", Route: "/api/nqe/repos/org/commits"},
	},
	"NQERepository.DeleteDirectory": {
		{Method: "POST", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.DeleteQuery": {
		{Method: "POST", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.DiscardChange": {
		{Method: "DELETE", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.DiscardChanges": {
		{Method: "POST", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.EditQuery": {
		{Method: "POST", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.GetDraft": {
		{Method: "GET", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.GetQuery": {
		{Method: "GET", Route: "/api/nqe/repos/org/commits/{commitId}/queries"},
	},
	"NQERepository.GetQueryByID": {
		{Method: "GET", Route: "/api/nqe/queries/{queryId}/source-code"},
	},
	"NQERepository.Head": {
		{Method: "GET", Route: "/api/nqe/repos/org/commits/head"},
	},
	"NQERepository.History": {
		{Method: "GET", Route: "/api/nqe/queries/{queryId}/history"},
	},
	"NQERepository.ListDrafts": {
		{Method: "GET", Route: "/api/users/current/nqe/changes"},
	},
	"NQERepository.ListHeadQueries": {
		{Method: "GET", Route: "/api/nqe/repos/org/commits/head/queries"},
	},
	"Networks.CheckAccess": {
		{Method: "GET", Route: "/api/networks"},
	},
	"Networks.Create": {
		{Method: "POST", Route: "/api/networks"},
	},
	"Networks.CreateWorkspace": {
		{Method: "POST", Route: "/api/networks/{networkId}/workspaces"},
	},
	"Networks.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}"},
	},
	"Networks.GetSnapshotRetentionPolicy": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshotRetentionPolicy"},
	},
	"Networks.L7Applications": {
		{Method: "GET", Route: "/api/l7-applications"},
	},
	"Networks.List": {
		{Method: "GET", Route: "/api/networks"},
	},
	"Networks.Paths": {
		{Method: "GET", Route: "/api/networks/{networkId}/paths"},
	},
	"Networks.PreviewSnapshotRetention": {
		{Method: "POST", Route: "/api/networks/{networkId}/snapshotRetentionPolicy/trigger"},
	},
	"Networks.SetSnapshotRetentionPolicy": {
		{Method: "PUT", Route: "/api/networks/{networkId}/snapshotRetentionPolicy"},
	},
	"Networks.Update": {
		{Method: "PATCH", Route: "/api/networks/{networkId}"},
	},
	"Organizations.Create": {
		{Method: "POST", Route: "/api/admin/orgs"},
	},
	"Organizations.Current": {
		{Method: "GET", Route: "/api/orgs/current"},
	},
	"Organizations.Delete": {
		{Method: "DELETE", Route: "/api/admin/orgs/{orgId}"},
	},
	"Organizations.List": {
		{Method: "GET", Route: "/api/admin/orgs"},
	},
	"Organizations.SetEnabled": {
		{Method: "POST", Route: "/api/admin/orgs/{orgId}"},
	},
	"Organizations.Update": {
		{Method: "PATCH", Route: "/api/admin/orgs/{orgId}"},
	},
	"Performance.DeviceMetricHistory": {
		{Method: "POST", Route: "/api/networks/{networkId}/device-metrics-history"},
	},
	"Performance.DeviceMetricHistoryDocument": {
		{Method: "POST", Route: "/api/networks/{networkId}/device-metrics-history"},
	},
	"Performance.DeviceMetrics": {
		{Method: "GET", Route: "/api/networks/{networkId}/device-metrics"},
	},
	"Performance.DeviceMetricsDocument": {
		{Method: "GET", Route: "/api/networks/{networkId}/device-metrics"},
	},
	"Performance.GenerateSynthetic": {
		{Method: "POST", Route: "/api/internal/networks/{networkId}/performance"},
	},
	"Performance.InterfaceMetricHistory": {
		{Method: "POST", Route: "/api/networks/{networkId}/interface-metrics-history"},
	},
	"Performance.InterfaceMetricHistoryDocument": {
		{Method: "POST", Route: "/api/networks/{networkId}/interface-metrics-history"},
	},
	"Performance.InterfaceMetrics": {
		{Method: "GET", Route: "/api/networks/{networkId}/interface-metrics"},
	},
	"Performance.InterfaceMetricsDocument": {
		{Method: "GET", Route: "/api/networks/{networkId}/interface-metrics"},
	},
	"Performance.UnhealthyDevices": {
		{Method: "GET", Route: "/api/networks/{networkId}/unhealthy-devices"},
	},
	"Performance.UnhealthyInterfaces": {
		{Method: "POST", Route: "/api/networks/{networkId}/unhealthy-interfaces"},
	},
	"Performance.Upload": {
		{Method: "POST", Route: "/api/networks/{networkId}/performance"},
	},
	"Performance.UploadWithIdentity": {
		{Method: "POST", Route: "/api/networks/{networkId}/performance"},
	},
	"Predict.AddSecurityRule": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/devices/{deviceName}/scopes/{scopeId}/rulebases/{rulebaseId}/security-rules"},
	},
	"Predict.Commit": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/commits"},
	},
	"Predict.CreateChangeSet": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets"},
	},
	"Predict.DeleteChangeSet": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/change-sets/{id}"},
	},
	"Predict.ListChangeSetChecks": {
		{Method: "GET", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/checks"},
	},
	"Predict.ListChangeSets": {
		{Method: "GET", Route: "/api/networks/{networkId}/change-sets"},
	},
	"Predict.ListPredictedSnapshots": {
		{Method: "GET", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/predicted-snapshots"},
	},
	"Predict.RemoveSecurityRule": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/devices/{deviceName}/scopes/{scopeId}/rulebases/{rulebaseId}/security-rules/{uuid}"},
	},
	"Predict.Run": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}"},
	},
	"Predict.RunOperation": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}"},
	},
	"Predict.SecurityRulesDiff": {
		{Method: "GET", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/devices/{deviceName}/security-rules-diff"},
	},
	"Predict.StageBGPAdvertisement": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/draft/devices/{device}/bgp-advertisements"},
	},
	"Predict.StageBGPAdvertisements": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/draft/devices/{device}/bgp-advertisements"},
	},
	"Predict.StageCommands": {
		{Method: "PUT", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/draft/devices/{device}/commands"},
	},
	"Predict.ValidateCommands": {
		{Method: "POST", Route: "/api/networks/{networkId}/change-sets/{changeSetId}/devices/{device}/commands"},
	},
	"Properties.ClearCurrent": {
		{Method: "DELETE", Route: "/api/config/{property}"},
	},
	"Properties.ClearGlobal": {
		{Method: "DELETE", Route: "/api/global-config/{property}"},
	},
	"Properties.ClearOrganization": {
		{Method: "DELETE", Route: "/api/orgs/{orgId}/config/software_central"},
	},
	"Properties.Current": {
		{Method: "GET", Route: "/api/config"},
	},
	"Properties.DescribeOrganization": {
		{Method: "GET", Route: "/api/global-config"},
		{Method: "GET", Route: "/api/orgs/{orgId}/config"},
	},
	"Properties.Global": {
		{Method: "GET", Route: "/api/global-config"},
	},
	"Properties.Organization": {
		{Method: "GET", Route: "/api/orgs/{orgId}/config"},
	},
	"Properties.SetCurrent": {
		{Method: "PUT", Route: "/api/config/{property}"},
	},
	"Properties.SetGlobal": {
		{Method: "PUT", Route: "/api/global-config/{property}"},
	},
	"Properties.SetOrganization": {
		{Method: "PUT", Route: "/api/orgs/{orgId}/config/{property}"},
	},
	"Proxies.Create": {
		{Method: "POST", Route: "/api/networks/{networkId}/proxies"},
	},
	"Proxies.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/proxies"},
	},
	"Proxies.Update": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/proxies/{proxyId}"},
	},
	"SAML.GetSettings": {
		{Method: "GET", Route: "/api/auth/saml-settings"},
	},
	"SAML.PutSettings": {
		{Method: "PUT", Route: "/api/auth/saml-settings"},
	},
	"Snapshots.Collect": {
		{Method: "GET", Route: "/api/collector-tasks/{taskId}"},
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
		{Method: "POST", Route: "/api/collector-tasks"},
	},
	"Snapshots.CollectionExceptions": {
		{Method: "GET", Route: "/api/collector/exceptions"},
	},
	"Snapshots.CollectionLog": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/collection-log"},
	},
	"Snapshots.CollectionMetrics": {
		{Method: "GET", Route: "/api/networks/{networkId}/collection-metrics"},
	},
	"Snapshots.ComputeAdvancedReachability": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.Delete": {
		{Method: "DELETE", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.Download": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.Exceptions": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/exceptions"},
	},
	"Snapshots.ExceptionsText": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/exceptions"},
	},
	"Snapshots.ExportSubset": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.ExportSubsetCompatibility": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.Favorite": {
		{Method: "PATCH", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.ForCollectionTask": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.Invalidate": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.LatestCollected": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.LatestProcessed": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.ListDocument": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.Logs": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/logs"},
	},
	"Snapshots.Metrics": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/metrics"},
	},
	"Snapshots.Operation": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.ProcessEstimate": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/processEstimate"},
	},
	"Snapshots.Progress": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/progress"},
	},
	"Snapshots.Reprocess": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.ResolveID": {
		{Method: "GET", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.SetNote": {
		{Method: "PATCH", Route: "/api/snapshots/{snapshotId}"},
	},
	"Snapshots.StartUploadOperation": {
		{Method: "POST", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.Upload": {
		{Method: "POST", Route: "/api/networks/{networkId}/snapshots"},
	},
	"Snapshots.UploadMergeCompatibility": {
		{Method: "POST", Route: "/api/networks/{networkId}/snapshots"},
	},
	"SoftwareCentral.DeploymentArtifactURL": {
		{Method: "GET", Route: "/api/deployment-artifacts/{artifactId}"},
	},
	"SoftwareCentral.DownloadClientPackage": {
		{Method: "GET", Route: "/api/software/client"},
	},
	"SoftwareCentral.DownloadDeploymentArtifact": {
		{Method: "GET", Route: "/api/deployment-artifacts/{artifactId}"},
	},
	"SoftwareCentral.ListDeploymentArtifacts": {
		{Method: "GET", Route: "/api/deployment-artifacts"},
	},
	"SoftwareCentral.ListForwardApplianceOVAs": {
		{Method: "GET", Route: "/api/deployment-artifacts"},
	},
	"SyntheticNodes.Backdate": {
		{Method: "POST", Route: "/api/networks/{networkId}/adjacent-networks"},
		{Method: "POST", Route: "/api/networks/{networkId}/internet-node"},
		{Method: "POST", Route: "/api/networks/{networkId}/intranet-nodes"},
		{Method: "POST", Route: "/api/networks/{networkId}/l2-vpns"},
		{Method: "POST", Route: "/api/networks/{networkId}/l3-vpns"},
	},
	"SyntheticNodes.CompatibleQueries": {
		{Method: "GET", Route: "/api/synthetic-device-queries"},
	},
	"SyntheticNodes.ComputeQuery": {
		{Method: "POST", Route: "/api/networks/{networkId}/adjacent-networks"},
		{Method: "POST", Route: "/api/networks/{networkId}/internet-node"},
		{Method: "POST", Route: "/api/networks/{networkId}/intranet-nodes"},
		{Method: "POST", Route: "/api/networks/{networkId}/l2-vpns"},
		{Method: "POST", Route: "/api/networks/{networkId}/l3-vpns"},
	},
	"SyntheticNodes.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/adjacent-networks/{adjacentNetworkName}"},
		{Method: "DELETE", Route: "/api/networks/{networkId}/intranet-nodes/{nodeName}"},
		{Method: "DELETE", Route: "/api/networks/{networkId}/l2-vpns/{l2VpnName}"},
		{Method: "DELETE", Route: "/api/networks/{networkId}/l3-vpns/{l3VpnName}"},
	},
	"SyntheticNodes.DeleteIntranetNode": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/intranet-nodes/{nodeName}"},
	},
	"SyntheticNodes.DeleteL3VPN": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/l3-vpns/{l3VpnName}"},
	},
	"SyntheticNodes.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/adjacent-networks/{adjacentNetworkName}"},
		{Method: "GET", Route: "/api/networks/{networkId}/internet-node"},
		{Method: "GET", Route: "/api/networks/{networkId}/intranet-nodes/{nodeName}"},
		{Method: "GET", Route: "/api/networks/{networkId}/l2-vpns/{l2VpnName}"},
		{Method: "GET", Route: "/api/networks/{networkId}/l3-vpns/{l3VpnName}"},
	},
	"SyntheticNodes.GetInternetNode": {
		{Method: "GET", Route: "/api/networks/{networkId}/internet-node"},
	},
	"SyntheticNodes.GetIntranetNode": {
		{Method: "GET", Route: "/api/networks/{networkId}/intranet-nodes/{nodeName}"},
	},
	"SyntheticNodes.GetL3VPN": {
		{Method: "GET", Route: "/api/networks/{networkId}/l3-vpns/{l3VpnName}"},
	},
	"SyntheticNodes.InternetConnectionSuggestions": {
		{Method: "GET", Route: "/api/networks/{networkId}/internet-node/connection-suggestions"},
	},
	"SyntheticNodes.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/adjacent-networks"},
		{Method: "GET", Route: "/api/networks/{networkId}/intranet-nodes"},
		{Method: "GET", Route: "/api/networks/{networkId}/l2-vpns"},
		{Method: "GET", Route: "/api/networks/{networkId}/l3-vpns"},
	},
	"SyntheticNodes.ListIntranetNodes": {
		{Method: "GET", Route: "/api/networks/{networkId}/intranet-nodes"},
	},
	"SyntheticNodes.ListL3VPNs": {
		{Method: "GET", Route: "/api/networks/{networkId}/l3-vpns"},
	},
	"SyntheticNodes.Put": {
		{Method: "PUT", Route: "/api/networks/{networkId}/internet-node"},
		{Method: "PUT", Route: "/api/networks/{networkId}/intranet-nodes/{nodeName}"},
		{Method: "PUT", Route: "/api/networks/{networkId}/l3-vpns/{l3VpnName}"},
	},
	"SyntheticNodes.PutInternetNode": {
		{Method: "PUT", Route: "/api/networks/{networkId}/internet-node"},
	},
	"SyntheticNodes.PutIntranetNode": {
		{Method: "PUT", Route: "/api/networks/{networkId}/intranet-nodes/{nodeName}"},
	},
	"SyntheticNodes.PutL3VPN": {
		{Method: "PUT", Route: "/api/networks/{networkId}/l3-vpns/{l3VpnName}"},
	},
	"SyntheticNodes.SetInternetExcludedSubnets": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/internet-node"},
	},
	"SyntheticNodes.SetQuery": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/adjacent-networks/{adjacentNetworkName}"},
		{Method: "PATCH", Route: "/api/networks/{networkId}/internet-node"},
		{Method: "PATCH", Route: "/api/networks/{networkId}/intranet-nodes/{nodeName}"},
		{Method: "PATCH", Route: "/api/networks/{networkId}/l2-vpns/{l2VpnName}"},
		{Method: "PATCH", Route: "/api/networks/{networkId}/l3-vpns/{l3VpnName}"},
	},
	"Topology.BackdateLinkOverrides": {
		{Method: "POST", Route: "/api/networks/{networkId}/link-overrides"},
	},
	"Topology.EditOverrides": {
		{Method: "POST", Route: "/api/snapshots/{snapshotId}/topology/overrides"},
	},
	"Topology.List": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/topology"},
	},
	"Topology.Overrides": {
		{Method: "GET", Route: "/api/snapshots/{snapshotId}/topology/overrides"},
	},
	"TrustedCertificates.Add": {
		{Method: "POST", Route: "/api/trusted-certificates"},
	},
	"TrustedCertificates.Apply": {
		{Method: "POST", Route: "/api/trusted-certificates"},
	},
	"TrustedCertificates.ApplyOperations": {
		{Method: "GET", Route: "/api/collector-tasks/{taskId}"},
		{Method: "POST", Route: "/api/trusted-certificates"},
	},
	"TrustedCertificates.Delete": {
		{Method: "DELETE", Route: "/api/trusted-certificates/{name}"},
	},
	"TrustedCertificates.List": {
		{Method: "GET", Route: "/api/trusted-certificates"},
	},
	"Users.AddNetworkRole": {
		{Method: "POST", Route: "/api/users/{userId}/roles/network/{networkId}/{role}"},
	},
	"Users.BulkSetEnabled": {
		{Method: "PATCH", Route: "/api/users"},
	},
	"Users.ClearNetworkRoles": {
		{Method: "DELETE", Route: "/api/users/{userId}/roles/network/{networkId}"},
	},
	"Users.Create": {
		{Method: "POST", Route: "/api/users"},
	},
	"Users.CreateToken": {
		{Method: "POST", Route: "/api/users/current/tokens"},
	},
	"Users.Current": {
		{Method: "GET", Route: "/api/users/current"},
	},
	"Users.CurrentSession": {
		{Method: "GET", Route: "/api/users/current"},
	},
	"Users.Delete": {
		{Method: "DELETE", Route: "/api/users/{userId}"},
	},
	"Users.DeleteToken": {
		{Method: "DELETE", Route: "/api/users/current/tokens/{tokenName}"},
	},
	"Users.DeleteTokenFor": {
		{Method: "DELETE", Route: "/api/users/{userId}/tokens/{tokenName}"},
	},
	"Users.Get": {
		{Method: "GET", Route: "/api/users/{userId}"},
	},
	"Users.GrantOrgAdmin": {
		{Method: "POST", Route: "/api/users/{userId}/roles/org/ADMIN"},
	},
	"Users.List": {
		{Method: "GET", Route: "/api/users"},
	},
	"Users.ListTokens": {
		{Method: "GET", Route: "/api/users/current/tokens"},
	},
	"Users.ListTokensFor": {
		{Method: "GET", Route: "/api/users/{userId}/tokens"},
	},
	"Users.ListWithRoles": {
		{Method: "GET", Route: "/api/users"},
	},
	"Users.Patch": {
		{Method: "PATCH", Route: "/api/users/{userId}"},
	},
	"Users.RemoveNetworkRole": {
		{Method: "DELETE", Route: "/api/users/{userId}/roles/network/{networkId}/{role}"},
	},
	"Users.Reset2FA": {
		{Method: "DELETE", Route: "/api/users/{userId}/2fa"},
	},
	"Users.ResetPassword": {
		{Method: "POST", Route: "/api/users/current/password"},
	},
	"Users.RevokeOrgAdmin": {
		{Method: "DELETE", Route: "/api/users/{userId}/roles/org/ADMIN"},
	},
	"Users.Roles": {
		{Method: "GET", Route: "/api/users/{userId}/roles"},
	},
	"Users.RolesDirect": {
		{Method: "GET", Route: "/api/users/{userId}/roles"},
	},
	"Users.SetNetworkRole": {
		{Method: "POST", Route: "/api/users/{userId}/roles/network/{networkId}"},
	},
	"Users.TwoFactorStatuses": {
		{Method: "GET", Route: "/api/users"},
	},
	"Version.Get": {
		{Method: "GET", Route: "/api/version"},
	},
	"Version.Reachable": {
		{Method: "GET", Route: "/api/version"},
	},
	"Vulnerabilities.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/vulnerabilities/{cveId}"},
	},
	"Vulnerabilities.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/vulnerabilities"},
	},
	"Vulnerabilities.ListByOS": {
		{Method: "GET", Route: "/api/networks/{networkId}/vulnerabilities"},
	},
	"Vulnerabilities.ListDevices": {
		{Method: "GET", Route: "/api/networks/{networkId}/device-vulnerabilities"},
	},
	"WanCircuits.Backdate": {
		{Method: "POST", Route: "/api/networks/{networkId}/wan-circuits"},
	},
	"WanCircuits.Delete": {
		{Method: "DELETE", Route: "/api/networks/{networkId}/wan-circuits/{wanCircuitName}"},
	},
	"WanCircuits.Get": {
		{Method: "GET", Route: "/api/networks/{networkId}/wan-circuits/{wanCircuitName}"},
	},
	"WanCircuits.List": {
		{Method: "GET", Route: "/api/networks/{networkId}/wan-circuits"},
	},
	"WanCircuits.Patch": {
		{Method: "PATCH", Route: "/api/networks/{networkId}/wan-circuits/{wanCircuitName}"},
	},
	"WanCircuits.Put": {
		{Method: "PUT", Route: "/api/networks/{networkId}/wan-circuits/{wanCircuitName}"},
	},
	"WanCircuits.ReplaceAll": {
		{Method: "PUT", Route: "/api/networks/{networkId}/wan-circuits"},
	},
	"Webhooks.Create": {
		{Method: "POST", Route: "/api/webhooks"},
	},
	"Webhooks.Delete": {
		{Method: "DELETE", Route: "/api/webhooks/{webhookName}"},
	},
	"Webhooks.List": {
		{Method: "GET", Route: "/api/webhooks"},
	},
	"Webhooks.TestNew": {
		{Method: "POST", Route: "/api/webhooks"},
	},
	"Webhooks.Update": {
		{Method: "PATCH", Route: "/api/webhooks/{name}"},
	},
}
