package forward

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// PredictService accesses Forward Predict and change-set APIs.
//
// Preview: these endpoints are not part of the published OpenAPI contract and
// may change between Forward releases. The SDK will evolve them during v0.x.
type PredictService service

// ChangeSetCreateRequest creates a Predict change set from a base snapshot.
// The network ID belongs in the request path and must not be included here.
//
// Predict does not model every CLI side effect. In affected appserver builds,
// CLI `network <prefix>` statements produce CONFIG protocol seeds; Predict has
// no CONFIG propagation strategy and silently discards those seeds. Model new
// BGP originations with StageBGPAdvertisement instead.
type ChangeSetCreateRequest struct {
	Name        string   `json:"name"`
	Description string   `json:"description,omitempty"`
	SnapshotID  string   `json:"snapshotId"`
	Tags        []string `json:"tags,omitempty"`
}

// ChangeSet is the common metadata returned for a Predict change set.
type ChangeSet struct {
	ID              Identifier                 `json:"id"`
	Name            string                     `json:"name"`
	Description     string                     `json:"description,omitempty"`
	NetworkID       Identifier                 `json:"networkId"`
	SnapshotID      Identifier                 `json:"snapshotId"`
	Tags            []string                   `json:"tags,omitempty"`
	DeviceToChanges map[string]json.RawMessage `json:"deviceToChanges,omitempty"`
}

// PredictedSnapshot is the subset of predicted snapshot metadata required to
// track processing. Additional server fields can be added without changing the
// prediction workflow.
type PredictedSnapshot struct {
	ID                Identifier `json:"id"`
	State             string     `json:"state"`
	CreatedAt         string     `json:"createdAt,omitempty"`
	ProcessedAt       string     `json:"processedAt,omitempty"`
	ProcessingTrigger string     `json:"processingTrigger,omitempty"`
	Note              string     `json:"note,omitempty"`
}

// BGPAdvertisement is an external advertisement staged in a Predict change
// set. Device identifies the receiving device and is placed in the URL, not the
// JSON body. This structured form is the only reliable way to add an origination
// to Predict on builds that discard CONFIG protocol seeds generated by CLI.
// Withdrawal is not modeled by Forward Predict and this SDK intentionally
// exposes no withdrawal action; callers must not interpret omission as one.
type BGPAdvertisement struct {
	Device       string   `json:"-"`
	VRF          string   `json:"vrf"`
	ExternalPeer string   `json:"externalPeer"`
	Prefix       string   `json:"prefix"`
	NextHop      string   `json:"nextHop"`
	Type         string   `json:"type"`
	Origin       string   `json:"origin"`
	LocalPref    *int64   `json:"localPref,omitempty"`
	ASPath       []int64  `json:"asPath"`
	MED          *int64   `json:"med,omitempty"`
	Communities  []string `json:"communities"`
}

// CreateChangeSet creates a Predict change set.
func (s *PredictService) CreateChangeSet(
	ctx context.Context,
	networkID string,
	request ChangeSetCreateRequest,
) (*ChangeSet, *Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, nil, err
	}
	path, err := changeSetsPath(networkID)
	if err != nil {
		return nil, nil, err
	}
	if strings.TrimSpace(request.Name) == "" || strings.TrimSpace(request.SnapshotID) == "" {
		return nil, nil, errors.New("forward: change-set name and base snapshot ID are required")
	}
	req, err := s.client.newJSONRequest(ctx, http.MethodPost, path, request)
	if err != nil {
		return nil, nil, err
	}
	changeSet := new(ChangeSet)
	resp, err := s.client.Do(req, changeSet)
	if err != nil {
		return nil, resp, err
	}
	s.client.observeCapability(CapabilityPredict)
	return changeSet, resp, nil
}

// ListChangeSets lists Predict change sets for a network.
func (s *PredictService) ListChangeSets(ctx context.Context, networkID string) ([]ChangeSet, *Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, nil, err
	}
	path, err := changeSetsPath(networkID)
	if err != nil {
		return nil, nil, err
	}
	req, err := s.client.NewRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, nil, err
	}
	result := listResponse[ChangeSet]{Keys: []string{"changeSets", "items"}}
	resp, err := s.client.Do(req, &result)
	if err != nil {
		return nil, resp, err
	}
	return result.Items, resp, nil
}

// DeleteChangeSet deletes a Predict change set.
func (s *PredictService) DeleteChangeSet(
	ctx context.Context,
	networkID string,
	changeSetID string,
) (*Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, err
	}
	path, err := changeSetPath(networkID, changeSetID)
	if err != nil {
		return nil, err
	}
	req, err := s.client.NewRequest(ctx, http.MethodDelete, path, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(req, nil)
}

// StageCommands replaces a device's draft CLI commands. Interactive wrapper
// lines are removed because Predict accepts configuration-mode content only.
// A CLI `network <prefix>` is still not a reliable BGP origination; use the
// structured StageBGPAdvertisement path described above.
func (s *PredictService) StageCommands(
	ctx context.Context,
	networkID string,
	changeSetID string,
	deviceName string,
	commands string,
) (*Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, err
	}
	path, err := predictDevicePath(networkID, changeSetID, deviceName)
	if err != nil {
		return nil, err
	}
	path += "/commands"
	req, err := s.client.NewRequest(ctx, http.MethodPut, path, strings.NewReader(cleanPredictCommands(commands)))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "text/plain;charset=UTF-8")
	response, err := s.client.Do(req, nil)
	if err == nil {
		s.client.observeCapability(CapabilityPredict)
	}
	return response, err
}

// StageBGPAdvertisement adds an external BGP advertisement to a device draft.
func (s *PredictService) StageBGPAdvertisement(
	ctx context.Context,
	networkID string,
	changeSetID string,
	advertisement BGPAdvertisement,
) (*Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, err
	}
	if err := s.client.requireCapability(CapabilityStructuredBGPAdvertisements); err != nil {
		return nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, err
	}
	path, err := predictDevicePath(networkID, changeSetID, advertisement.Device)
	if err != nil {
		return nil, err
	}
	path += "/bgp-advertisements?action=add"
	if advertisement.ASPath == nil {
		advertisement.ASPath = []int64{}
	}
	if advertisement.Communities == nil {
		advertisement.Communities = []string{}
	}
	req, err := s.client.newJSONRequest(ctx, http.MethodPost, path, advertisement)
	if err != nil {
		return nil, err
	}
	response, err := s.client.Do(req, nil)
	if err == nil {
		s.client.observeCapability(CapabilityPredict)
		s.client.observeCapability(CapabilityStructuredBGPAdvertisements)
	}
	return response, err
}

// Run starts predictive analysis and returns the newly created predicted
// snapshot metadata. Processing continues asynchronously.
func (s *PredictService) Run(
	ctx context.Context,
	networkID string,
	changeSetID string,
	note string,
) (*PredictedSnapshot, *Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, nil, err
	}
	path, err := changeSetPath(networkID, changeSetID)
	if err != nil {
		return nil, nil, err
	}
	params := url.Values{"action": []string{"predict"}, "note": []string{note}}
	path += "?" + params.Encode()
	req, err := s.client.NewRequest(ctx, http.MethodPost, path, nil)
	if err != nil {
		return nil, nil, err
	}
	snapshot := new(PredictedSnapshot)
	resp, err := s.client.Do(req, snapshot)
	if err != nil {
		return nil, resp, err
	}
	s.client.observeCapability(CapabilityPredict)
	return snapshot, resp, nil
}

// RunOperation starts Predict and returns a handle that polls the predicted
// snapshot metadata route until processing reaches a terminal state.
func (s *PredictService) RunOperation(
	ctx context.Context,
	networkID string,
	changeSetID string,
	note string,
) (*Poller[Snapshot], *Response, error) {
	predicted, response, err := s.Run(ctx, networkID, changeSetID, note)
	if err != nil {
		return nil, response, err
	}
	initial := &Snapshot{ID: predicted.ID, State: predicted.State, CreatedAt: predicted.CreatedAt, ProcessedAt: predicted.ProcessedAt, ProcessingTrigger: predicted.ProcessingTrigger, Note: predicted.Note}
	poller, err := NewPoller(initial, func(ctx context.Context) (*Snapshot, *Response, error) {
		return s.client.Snapshots.Get(ctx, networkID, string(predicted.ID))
	}, snapshotProcessingDone)
	return poller, response, err
}

func snapshotProcessingDone(snapshot *Snapshot) (bool, error) {
	switch strings.ToUpper(snapshot.State) {
	case "PROCESSED":
		return true, nil
	case "FAILED", "CANCELED", "TIMED_OUT", "RESTORE_FAILED":
		return true, fmt.Errorf("forward: snapshot %s ended with state %s", snapshot.ID, snapshot.State)
	default:
		return false, nil
	}
}

// ListPredictedSnapshots returns the prediction history for a change set.
func (s *PredictService) ListPredictedSnapshots(
	ctx context.Context,
	networkID string,
	changeSetID string,
) ([]PredictedSnapshot, *Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, nil, err
	}
	path, err := changeSetPath(networkID, changeSetID)
	if err != nil {
		return nil, nil, err
	}
	path += "/predicted-snapshots"
	req, err := s.client.NewRequest(ctx, http.MethodGet, path, nil)
	if err != nil {
		return nil, nil, err
	}
	result := listResponse[PredictedSnapshot]{Keys: []string{"snapshots", "predictedSnapshots", "items"}}
	resp, err := s.client.Do(req, &result)
	if err != nil {
		return nil, resp, err
	}
	return result.Items, resp, nil
}

func cleanPredictCommands(commands string) string {
	drop := map[string]bool{
		"enable": true, "write memory": true, "write mem": true,
		"wr mem": true, "wr": true, "!": true, "exit": true,
	}
	lines := strings.Split(commands, "\n")
	kept := lines[:0]
	for _, line := range lines {
		if !drop[strings.ToLower(strings.TrimSpace(line))] {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}

func changeSetsPath(networkID string) (string, error) {
	networkID = strings.TrimSpace(networkID)
	if networkID == "" {
		return "", errors.New("forward: network ID is required")
	}
	return fmt.Sprintf("/api/networks/%s/change-sets", url.PathEscape(networkID)), nil
}

func changeSetPath(networkID, changeSetID string) (string, error) {
	path, err := changeSetsPath(networkID)
	if err != nil {
		return "", err
	}
	changeSetID = strings.TrimSpace(changeSetID)
	if changeSetID == "" {
		return "", errors.New("forward: change-set ID is required")
	}
	return path + "/" + url.PathEscape(changeSetID), nil
}

func predictDevicePath(networkID, changeSetID, deviceName string) (string, error) {
	path, err := changeSetPath(networkID, changeSetID)
	if err != nil {
		return "", err
	}
	deviceName = strings.TrimSpace(deviceName)
	if deviceName == "" {
		return "", errors.New("forward: device name is required")
	}
	return fmt.Sprintf("%s/draft/devices/%s", path, url.PathEscape(deviceName)), nil
}

// CloudChanges is a provider-neutral statement of what a cloud collection
// source should look like after a change.
//
// A caller names a route table and a destination, or a security group and a
// rule, without knowing which provider's state files Predict will edit. The
// server refuses a change a provider has no predictor for, so an AWS-only kind
// stated against Azure comes back as a 400 rather than being ignored.
type CloudChanges struct {
	RouteChanges          []CloudRouteChange          `json:"routeChanges,omitempty"`
	SecurityRuleChanges   []CloudSecurityRuleChange   `json:"securityRuleChanges,omitempty"`
	TgwAssociationChanges []CloudTgwAssociationChange `json:"tgwAssociationChanges,omitempty"`
	TgwPropagationChanges []CloudTgwPropagationChange `json:"tgwPropagationChanges,omitempty"`
	VpnRouteChanges       []CloudVpnRouteChange       `json:"vpnRouteChanges,omitempty"`
}

// CloudRouteChange adds, retargets or removes one route. A destination names
// at most one route in a table, so restating it retargets; an absent Target
// removes it.
type CloudRouteChange struct {
	RouteTableID         string            `json:"routeTableId"`
	DestinationCidrBlock string            `json:"destinationCidrBlock"`
	Target               *CloudRouteTarget `json:"target,omitempty"`
}

// CloudRouteTarget is where a route points. Kind is an AwsRouteTarget name for
// AWS and an AzureNextHopType name for Azure.
type CloudRouteTarget struct {
	Kind string `json:"kind"`
	ID   string `json:"id"`
}

// CloudSecurityRuleChange states exactly one of Addition or RemovedRuleID.
type CloudSecurityRuleChange struct {
	SecurityGroupID string             `json:"securityGroupId"`
	Addition        *CloudRuleAddition `json:"addition,omitempty"`
	RemovedRuleID   string             `json:"removedRuleId,omitempty"`
}

// CloudRuleAddition is a security rule stated as its own fields.
//
// Shaped by what AWS needs, where a collected rule carries no id of its own and
// every rule is an unordered allow. Name, Priority and Deny are what a richer
// provider needs on top: Azure names each rule, orders them by priority, and
// lets one deny.
type CloudRuleAddition struct {
	Egress      bool   `json:"egress"`
	Protocol    string `json:"protocol"`
	FromPort    *int64 `json:"fromPort,omitempty"`
	ToPort      *int64 `json:"toPort,omitempty"`
	TargetKind  string `json:"targetKind"`
	TargetID    string `json:"targetId"`
	Description string `json:"description"`
	Name        string `json:"name,omitempty"`
	Priority    *int64 `json:"priority,omitempty"`
	Deny        bool   `json:"deny,omitempty"`
}

// CloudTgwAssociationChange retargets an attachment; an absent RouteTableID
// disassociates it.
type CloudTgwAssociationChange struct {
	AttachmentID string `json:"attachmentId"`
	RouteTableID string `json:"routeTableId,omitempty"`
}

// CloudTgwPropagationChange states whether an attachment's prefixes are learned
// into a route table. The pair is the identity, so Enabled says whether the
// membership exists.
type CloudTgwPropagationChange struct {
	RouteTableID string `json:"routeTableId"`
	AttachmentID string `json:"attachmentId"`
	Enabled      bool   `json:"enabled"`
}

// CloudVpnRouteChange states a destination a VPN connection carries.
//
// Only a statically routed connection states its own destinations; a BGP
// connection learns them from the peer and is refused. What a connection
// carries is what its gateway propagates into the VPC route tables.
type CloudVpnRouteChange struct {
	VpnConnectionID      string `json:"vpnConnectionId"`
	DestinationCidrBlock string `json:"destinationCidrBlock"`
	Present              bool   `json:"present"`
}

// StageCloudChanges replaces the cloud changes staged for a collection source.
//
// SourceName names a collection *source*, not a device: a cloud source models
// many devices, none of which is a device by the source's own name.
func (s *PredictService) StageCloudChanges(
	ctx context.Context,
	networkID string,
	changeSetID string,
	sourceName string,
	changes CloudChanges,
) (*Response, error) {
	return s.stageCloud(ctx, networkID, changeSetID, sourceName, "", changes)
}

// StageTerraformPlan translates `terraform show -json` output into cloud
// changes and stages them.
//
// The server reports what it could not translate rather than dropping it, so a
// plan touching resources Predict has no predictor for is not silently taken
// as a smaller change than it is.
func (s *PredictService) StageTerraformPlan(
	ctx context.Context,
	networkID string,
	changeSetID string,
	sourceName string,
	planJSON []byte,
) (*Response, error) {
	return s.stageCloud(ctx, networkID, changeSetID, sourceName, "fromTerraformPlan", json.RawMessage(planJSON))
}

func (s *PredictService) stageCloud(
	ctx context.Context,
	networkID string,
	changeSetID string,
	sourceName string,
	action string,
	body any,
) (*Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, err
	}
	if err := s.client.requireCapability(CapabilityCloudPredict); err != nil {
		return nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, err
	}
	path, err := predictDevicePath(networkID, changeSetID, sourceName)
	if err != nil {
		return nil, err
	}
	path += "/cloud-changes"
	if action != "" {
		path += "?" + url.Values{"action": []string{action}}.Encode()
	}
	req, err := s.client.newJSONRequest(ctx, http.MethodPost, path, body)
	if err != nil {
		return nil, err
	}
	response, err := s.client.Do(req, nil)
	if err == nil {
		s.client.observeCapability(CapabilityPredict)
		s.client.observeCapability(CapabilityCloudPredict)
	}
	return response, err
}

// Commit records the staged draft as a commit on the change set, which is what
// Predict then runs against.
func (s *PredictService) Commit(
	ctx context.Context,
	networkID string,
	changeSetID string,
	note string,
) (*Response, error) {
	if err := s.client.requireCapability(CapabilityPredict); err != nil {
		return nil, err
	}
	networkID, err := s.client.resolveNetworkID(networkID)
	if err != nil {
		return nil, err
	}
	path, err := changeSetPath(networkID, changeSetID)
	if err != nil {
		return nil, err
	}
	path += "/commits?" + url.Values{"note": []string{note}}.Encode()
	req, err := s.client.NewRequest(ctx, http.MethodPost, path, nil)
	if err != nil {
		return nil, err
	}
	response, err := s.client.Do(req, nil)
	if err == nil {
		s.client.observeCapability(CapabilityPredict)
	}
	return response, err
}
