package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type manifest struct {
	SchemaVersion        int        `json:"schema_version"`
	Consumer             string     `json:"consumer"`
	DerivedFrom          string     `json:"derived_from"`
	SemanticCallSites    int        `json:"semantic_call_sites"`
	DistinctMethodRoutes int        `json:"distinct_method_routes"`
	Endpoints            []endpoint `json:"endpoints"`
}

type endpoint struct {
	Method   string   `json:"method"`
	Route    string   `json:"route"`
	Symbols  []string `json:"symbols"`
	Coverage string   `json:"coverage"`
}

func main() {
	manifestPath := flag.String("manifest", "coverage_manifest.json", "coverage manifest")
	catalogPath := flag.String("catalog", "coverage_catalog_gen.go", "generated Go catalog")
	markdownPath := flag.String("markdown", "COVERAGE.md", "generated coverage matrix")
	flag.Parse()

	data, err := os.ReadFile(*manifestPath)
	must(err)
	var input manifest
	must(json.Unmarshal(data, &input))
	if len(input.Endpoints) != input.DistinctMethodRoutes {
		must(fmt.Errorf("manifest endpoint count %d != declared %d", len(input.Endpoints), input.DistinctMethodRoutes))
	}
	sort.Slice(input.Endpoints, func(i, j int) bool {
		left, right := input.Endpoints[i], input.Endpoints[j]
		return left.Method+" "+left.Route < right.Method+" "+right.Route
	})
	must(writeCatalog(*catalogPath, input.Endpoints))
	must(writeMarkdown(*markdownPath, input))
}

// writeCatalog emits one entry per SDK symbol listing EVERY method+route it
// can send. A symbol may appear on several endpoints: a kind-dependent method
// (SyntheticNodes.Get addresses the internet node, an intranet node or an L3
// VPN) and a composite (Diffs.MaterialSummary fans out to every diff count)
// send more than one route, and a consumer's route-liveness check can only
// verify the routes listed here.
func writeCatalog(path string, endpoints []endpoint) error {
	bySymbol := map[string][]endpoint{}
	for _, endpoint := range endpoints {
		for _, symbol := range endpoint.Symbols {
			for _, previous := range bySymbol[symbol] {
				if previous.Method == endpoint.Method && previous.Route == endpoint.Route {
					return fmt.Errorf("symbol %s is listed twice on %s %s", symbol, endpoint.Method, endpoint.Route)
				}
			}
			bySymbol[symbol] = append(bySymbol[symbol], endpoint)
		}
	}
	symbols := make([]string, 0, len(bySymbol))
	for symbol := range bySymbol {
		symbols = append(symbols, symbol)
	}
	sort.Strings(symbols)
	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/coveragegen; DO NOT EDIT.\n\npackage forward\n\n")
	out.WriteString("var sdkCoverageCatalog = map[string][]CoverageOperation{\n")
	for _, symbol := range symbols {
		fmt.Fprintf(&out, "\t%q: {\n", symbol)
		for _, endpoint := range bySymbol[symbol] {
			fmt.Fprintf(&out, "\t\t{Method: %q, Route: %q},\n", endpoint.Method, endpoint.Route)
		}
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

func writeMarkdown(path string, input manifest) error {
	var out bytes.Buffer
	out.WriteString("# Forward API typed coverage\n\n")
	fmt.Fprintf(&out, "This file is generated from `coverage_manifest.json`; run `go generate ./...` to refresh it. The manifest was derived from %s.\n\n", input.DerivedFrom)
	fmt.Fprintf(&out, "Current inventory: **%d semantic call sites**, **%d distinct normalized method+route pairs**, **%d COVERED**, **0 PARTIAL**, **0 MISSING**.\n\n", input.SemanticCallSites, input.DistinctMethodRoutes, input.DistinctMethodRoutes)
	out.WriteString("The inventory becomes stale when the consumer adds, removes, or changes a Forward wire call. Run `go run ./cmd/coverage-audit -audit /path/to/consumer/api-audit.md` to diff the audited route set. The command fails when its audit input is missing.\n\n")
	out.WriteString("| Method | Normalized route | Typed SDK symbol(s) | Class |\n|---|---|---|---|\n")
	for _, endpoint := range input.Endpoints {
		fmt.Fprintf(&out, "| %s | `%s` | `%s` | %s |\n", endpoint.Method, strings.ReplaceAll(endpoint.Route, "|", "\\|"), strings.Join(endpoint.Symbols, "`, `"), endpoint.Coverage)
	}
	return os.WriteFile(path, out.Bytes(), 0o644)
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
